name = "astrobobo-cron"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "ORDERS"
id = "21feab89e396426dbbf0752cd216ca78"

[triggers]
crons = ["0 6 * * *", "0 0 * * SUN"]

# Secrets: set via wrangler secret put
# OPENAI_API_KEY
# ONESIGNAL_APP_ID
# ONESIGNAL_API_KEY
