name = "astrobobo"
compatibility_date = "2024-01-01"
pages_build_output_dir = "../web"

[[kv_namespaces]]
binding = "ORDERS"
id = "21feab89e396426dbbf0752cd216ca78"

# Secrets via dashboard or wrangler secret put
# - OPENAI_API_KEY
# - ONESIGNAL_APP_ID
# - ONESIGNAL_API_KEY
